---

- include: RedHat.yml
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat')

- include: Ubuntu.yml
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- include: plugin.yml
#  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
