- name: vagrant | Create temporary directory
  tempfile:
    state: directory
    suffix: staging
#    path: "{{ lookup('env', 'HOME') }}"
  register: tempdir
  changed_when: false
  become: true

- name: vagrant | Install libvirt requirements (Debian only)
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state|default('present') }} update_cache=yes"
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and vagrant_libvirt_enabled
  become: true
  with_items:
    - libxslt-dev
    - libxml2-dev
    - libvirt-dev
    
- name: vagrant | Download vagrant
  get_url:
    url: "{{ vagrant_url }}.deb"
    dest: "{{ vagrant_dir_tmp }}/vagrant.deb"
    force: yes
  become: true
  tags:
    - vagrant

- name: vagrant | Install vagrant
  command: dpkg -i {{ vagrant_dir_tmp }}/vagrant.deb
  become: true
  tags:
    - vagrant

- name: vagrant | Cleanup temporary directory
  file: name={{ vagrant_dir_tmp }} state=absent
  tags:
    - vagrant
  changed_when: false
  ignore_errors: yes
  become: true
